(** A client-assigned order identifier.

    Clients choose their own order IDs before submitting, so they can refer
    to an order (e.g., to cancel it) without waiting for the exchange to
    respond with a server-side order ID. Client order IDs are scoped per
    participant — two different clients can independently choose the same ID
    without conflict.

    This is distinct from [Order_id.t], which is the exchange's internal,
    globally-unique identifier used for price-time priority and internal
    bookkeeping. *)

open! Core

type t [@@deriving sexp, bin_io, compare, equal, hash, string]

include Comparable.S with type t := t
include Hashable.S with type t := t

(** Wrap/unwrap the underlying integer. Exposed directly because the client
    chooses these IDs — they are not generated by the exchange. *)
val of_int : int -> t

val to_int : t -> int

(** A source of fresh client order IDs for a single client. Each bot keeps
    one generator and pulls a new ID for every order it submits, giving it a
    predictable, collision-free namespace it can later use to cancel.

    IDs are handed out sequentially from [0]; a fresh generator is
    independent of every other, matching the per-participant scoping of {!t}. *)
module Generator : sig
  type order_id := t
  type t [@@deriving sexp_of]

  val create : unit -> t

  (** Return the next unused ID and advance the generator. *)
  val next : t -> order_id
end
